SuperHeroesInc.UI/Controllers/CourseTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperHeroesInc.DATA;

namespace SuperHeroesInc.UI.Controllers
{
    public class CourseTypesController : Controller
    {
        private SuperHeroesIncVilHeroEntities db = new SuperHeroesIncVilHeroEntities();

        // GET: CourseTypes
        public ActionResult Index()
        {
            return View(db.CourseTypes1.ToList());
        }

        // GET: CourseTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseTypes courseTypes = db.CourseTypes1.Find(id);
            if (courseTypes == null)
            {
                return HttpNotFound();
            }
            return View(courseTypes);
        }

        // GET: CourseTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CourseTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseTypeID,Name,Description")] CourseTypes courseTypes)
        {
            if (ModelState.IsValid)
            {
                db.CourseTypes1.Add(courseTypes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(courseTypes);
        }

        // GET: CourseTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseTypes courseTypes = db.CourseTypes1.Find(id);
            if (courseTypes == null)
            {
                return HttpNotFound();
            }
            return View(courseTypes);
        }

        // POST: CourseTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseTypeID,Name,Description")] CourseTypes courseTypes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courseTypes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(courseTypes);
        }

        // GET: CourseTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CourseTypes courseTypes = db.CourseTypes1.Find(id);
            if (courseTypes == null)
            {
                return HttpNotFound();
            }
            return View(courseTypes);
        }

        // POST: CourseTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CourseTypes courseTypes = db.CourseTypes1.Find(id);
            db.CourseTypes1.Remove(courseTypes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SuperHeroesInc.UI/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SuperHeroesInc.DATA;

namespace SuperHeroesInc.UI.Controllers
{
    public class CoursesController : Controller
    {
        private SuperHeroesIncVilHeroEntities db = new SuperHeroesIncVilHeroEntities();

        // GET: Courses
        public ActionResult Index()
        {
            var courses1 = db.Courses1.Include(c => c.CourseType);
            return View(courses1.ToList());
        }

        // GET: Courses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses1.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        // GET: Courses/Create
        public ActionResult Create()
        {
            ViewBag.CourseTypeID = new SelectList(db.CourseTypes1, "CourseTypeID", "Name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CourseID,Name,Description,CourseTypeID")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                db.Courses1.Add(courses);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseTypeID = new SelectList(db.CourseTypes1, "CourseTypeID", "Name", courses.CourseTypeID);
            return View(courses);
        }

        // GET: Courses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses1.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseTypeID = new SelectList(db.CourseTypes1, "CourseTypeID", "Name", courses.CourseTypeID);
            return View(courses);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CourseID,Name,Description,CourseTypeID")] Courses courses)
        {
            if (ModelState.IsValid)
            {
                db.Entry(courses).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseTypeID = new SelectList(db.CourseTypes1, "CourseTypeID", "Name", courses.CourseTypeID);
            return View(courses);
        }

        // GET: Courses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Courses courses = db.Courses1.Find(id);
            if (courses == null)
            {
                return HttpNotFound();
            }
            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Courses courses = db.Courses1.Find(id);
            db.Courses1.Remove(courses);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SuperHeroesInc.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Super Heros Inc | @ViewBag.Title</title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!-- Bootstrap -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
    <!-- MaterialCSS -->
    <link rel="stylesheet" href="~/Content/css/material.min.css">
    <!-- RipplesCSS -->
    <link rel="stylesheet" href="~/Content/css/ripples.min.css">

    <!-- ThemeCSS & Responsive CSS -->
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/css/responsive.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <header class="header">
        <div data-velocity="-.4" id="particles" class="header-bg"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">]
                    @Html.Partial("_LoginPartial")
                   
                    <div class="social-links">
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="https://twitter.com/superheroorg"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-instagram"></i> <div class="ripple-wrapper"></div></a>
                    </div>
                </div>
            </div>
        </div>

        <div class="site-title-table">
            <div class="site-title-tablecell">
                <div class="slide-text">
                    <h2><a href="~/Views/Home/Index.cshtml"><span>S</span>uper<span>H</span>eros</a><span>I</span>nc.</h2>
                    <p>Our mission is to provide protection against villains and educate our community about safety.  We hope to develop a community of pro-active citizens who are vigilant in keeping streets safe through knowledge and awareness. </p>
                </div>
            </div>
        </div>
    </header>
    <section class="maincontent-wrap">

        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="maincotnent shadow-z-1">
                        <div class="mainmenu">
                            <div class="navbar navbar-nobg">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="navbar-collapse collapse">
                                    <ul class="nav navbar-nav">
                                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                        <li>@Html.ActionLink("About", "About", "Home")</li>
                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                        <li>@Html.ActionLink("Characters", "Index", "Characters")</li>
                                        <li>@Html.ActionLink("Training", "Index", "Courses")</li>
                                        <li>@Html.ActionLink("Class of Courses", "Index", "CourseTypes")</li>
                                        <li>@Html.ActionLink("Locations", "Index", "Locations")</li>
                                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                                        {
                                            <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                                            <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-10 col-md-offset-1"> 
                            </div>
                        </div>
                        @RenderBody()                    
                    </div> 
                                   
                </div>
               
            </div>
        </div>
    </section>
        

        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-5 col-md-6 col-lg-offset-1">
                        <div class="footer-wid">
                            <h2 class="wid-title">A<span>vengers</span></h2>
                            <p>
                                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis
                                nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan,
                            </p>
                        </div>
                    </div>
                    <div class="col-lg-5 col-md-6">
                        <div class="footer-wid">
                            <h2 class="wid-title">Newsletter</h2>
                            <p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>

                            <div class="newsletter-form">
                                <form action="index.html">
                                    <input class="shadow-z-1" type="email" placeholder="Your Email address">
                                    <button type="submit" class="btn btn-material-red">Subscribe Now!</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="footer-bottom">
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="copyright-text">
                                        <p>© 2015 Avengers - All Rights Reserved. Coded with <i class="fa fa-heart"></i> by <a href="http://wpexpand.com" target="_blank">WP Expand</a></p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="social-links footer-social-links">
                                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-google-plus"></i> <div class="ripple-wrapper"></div></a>
                                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-youtube"></i> <div class="ripple-wrapper"></div></a>
                                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-linkedin"></i> <div class="ripple-wrapper"></div></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </footer>


        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="~/Content/js/vendor/jquery-1.11.2.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="~/Content/js/bootstrap.min.js"></script>
        <script src="~/Content/js/material.min.js"></script>
        <script src="~/Content/js/ripples.min.js"></script>
        <script src="~/Content/js/jquery.scrolly.js"></script>
        <script src="~/Content/js/jquery.particleground.min.js"></script>
        <script src="~/Content/js/main.js"></script>
        @RenderSection("scripts", false)
</body>
</html>